version: '3.8'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: kallan_db
      POSTGRES_USER: kallan
      POSTGRES_PASSWORD: kallan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kallan -d kallan_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: kallan
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kallan_db
      SPRING_DATASOURCE_USERNAME: kallan
      SPRING_DATASOURCE_PASSWORD: kallan
      API_KEY: AIzaSyAilSjQ_55nmcWBBKvVpVkqDjThhLVQd1U
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  redis_data:
  postgres_data: