  version: '3.8'
  services:
    postgres:
      image: postgres:latest
      environment:
        POSTGRES_DB: kallan_db
        POSTGRES_USER: kallan
        POSTGRES_PASSWORD: kallan
      ports:
        - "5432:5432"

    app:
      build: .
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kallan_db
        SPRING_DATASOURCE_USERNAME: kallan
        SPRING_DATASOURCE_PASSWORD: kallan
      depends_on:
        - postgres
